surface_segmentation:
  # Scene cropping
  crop_min_x: 0
  crop_max_x: 1.2
  crop_min_y: -0.25
  crop_max_y: 0.25
  crop_min_z: 0.1
  crop_max_z: 1.5
  
  # Plane detection
  horizontal_tolerance_degrees: 10.0
  margin_above_surface: 0.015
  # Multi-plane detection
  min_surface_size: 8000
  max_point_distance: 0.01
  min_surface_exploration_iteration: 300
  
  # Clustering
  cluster_distance: 0.025
  min_cluster_size: 200
  max_cluster_size: 20000
  
  # For downsampling saved point clouds
  vox_leaf_size: 0.01
